---
title: "regr_m_ch01"
author: "SS Huh"
date: '2020 12 5 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 산점도


```{r }
market <-  read.table("market-1.txt", header=T)
head(market)
plot(market$X, market$Y, xlab="광고료", ylab="총판매액", pch=19)
title("광고료와판매액의산점도")
```

## 최소제곱법

$$
Y_{i}=\beta _{0} + \beta _{1}X_{i}+\varepsilon _{i}
$$
$$
S=\sum_{i=1}^{n}(Y_{i}-\beta _{0} - \beta _{1}X_{i})^2, 이를  \beta _{0},\beta _{1}으로 편미분하여 이를 0으로 만드는 값을 구하면...
$$
$$
b_1=\frac{\sum(X_i-\overline{X}) (Y_i-\overline{Y})}{\sum (X_i-\overline{X})^2}=\frac{S_{XY}}{S_{XX}}, b_0=\overline{Y}-b_1\overline{X}
$$

```{r }
market.lm = lm(Y ~ X, data=market)
summary(market.lm)
```

$$
\widehat{Y}=0.3282+2.1497X
$$

```{r }
plot(market$X, market$Y, xlab="광고료", ylab="총판매액", pch=19)
title("광고료와판매액의산점도")

abline(market.lm)
identify(market$X, market$Y)

names(market.lm)
market.lm$resid

xbar= mean(market$X)
ybar= mean(market$Y)
points(xbar, ybar, pch=17, cex=2.0, col='RED')
text(xbar, ybar, "(8.85, 19.36)")
fx<-"Y-hat = 0.328+2.14*X"
#text(locator(1), fx)
```
```{r }

sum(market.lm$resid)

resid= market.lm$residuals
fitted = market.lm$fitted
sum(resid)
```

```{r }
sum(fitted)
sum(market$Y)
```
```{r }
sum(market$X * resid)  #잔차의 특성 - 수직관계 확인
sum(market$X * market.lm$resid)
sum(fitted * resid)    #잔차의 특성 - 수직관계 확인
```
```{r }
#분산분석표에 의한 F검정
anova(market.lm)

qf(0.95,1,13)
1-pf(192.9,1,13)
```

```{r }
#추정값의 신뢰구간간
pred.frame= data.frame(X=seq(3.5, 14.5, 0.2))
pc = predict(market.lm, int="c", newdata=pred.frame) #기댓값신뢰구간
pp = predict(market.lm, int="p", newdata=pred.frame) #새로운값 신뢰구간
head(pc, 3)
head(pp, 3)

pred.X= pred.frame$X
plot(market$X, market$Y, ylim=range(market$Y, pp))
matlines(pred.X, pc, lty=c(1,2,2), col="BLUE")
matlines(pred.X, pp, lty=c(1,3,3), col="RED")


```

```{r }
#Beta의 검정
# 유의수준 0.05 기각역
qt(0.975, 13)
# 유의확률 p-값
2*(1-pt(13.889, 13))

#가중회귀
x = c(1,2,3,4,5)
y = c(2,3,5,8,7)
w = 1/x
w.lm= lm(y ~ x, weights=w)
summary(w.lm)
anova(w.lm)
```
